backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "schedule"
    label: "Mass Schedule"
    label_singular: "Mass Day"
    editor:
      preview: false
    files:
      - file: "data/schedule.json"
        label: "Mass Schedule"
        name: "mass_schedule"
        format: "json"
        fields:
          - label: "Days"
            name: ""
            widget: "list"
            fields:
              - { label: "Day", name: "day", widget: "string" }
              - {
                  label: "Mass Times",
                  name: "times",
                  widget: "list",
                  summary: "{{fields.times}}"
                }

  - name: "carousel"
    label: "Carousel News"
    label_singular: "Event"
    editor:
      preview: false
    files:
      - file: "data/carousel.json"
        label: "News Carousel"
        name: "carousel_items"
        format: "json"
        fields:
          - label: "Events"
            name: ""
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
